
# sorry I made a mistake I shouldn't have deleted main_1
# now it is back

a = 333
print('OK')
